source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'lodash_utility_Example', :exclusive => true do
  pod "lodash_utility", :path => "../"
end

target 'lodash_utility_Tests', :exclusive => true do
  pod "lodash_utility", :path => "../"

  
end
